### ISSUE TITLE
Installation Error:(unittest.sh)

### ISSUE THREAD

**Issue by VidhyaApple** [pkp/xmlps#2] opened 2014-12-16 06:40 UTC
When I run unittest.sh, it errors out.

Errors:

PHPUnit 3.7.29 by Sebastian Bergmann.

Configuration read from /home/quotequadsco/public_html/xmlps/phpunit.xml

.................FstdClass Object
(
    [error] => File name (fileName) parameter is missing.
    [status] => error
    [flashMessages] => Array
        (
        )

)

Time: 4.17 seconds, Memory: 43.00Mb

There was 1 failure:

1) ApiTest\Controller\ApiControllerTest::testSubmitAction
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-error
+success

/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobControllerTest.php:64

FAILURES!
Tests: 18, Assertions: 56, Failures: 1.

**Comment by axfelix** [comment] 2015-01-05 23:31
Hi Vidhya,

In my last response, I was referring to having fixed the web interface at pkp-udev; I'm not sure if we were misunderstanding one another or not. Regardless, everything should now be fixed, including the unit tests (which were indeed written against an earlier version of the api POST functionality). Please do a fresh checkout and let me know how it works.

**Comment by VidhyaApple** [comment] 2015-01-06 09:46
I updated the changes and tried unittest. getting following errors 

root@gains [/home/quotequadsco/public_html/xmlps]# ./unittest.sh
PHPUnit 3.7.29 by Sebastian Bergmann.

Configuration read from /home/quotequadsco/public_html/xmlps/phpunit.xml

................E

Time: 3.98 seconds, Memory: 41.00Mb

There was 1 error:

1) ApiTest\Controller\ApiControllerTest::testSubmitActionCannotBeAccessedLoggedO                                                                                                                                                ut
Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO                                                                                                                                                 document (path, conversionStage, mimeType, size, jobId) VALUES (?, ?, ?, ?, ?)'                                                                                                                                                 with params ["\/tmp\/UNITTEST_document.txt", 10, null, 9, 130]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mimeType' cannot b                                                                                                                                                e null

/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBAL                                                                                                                                                Exception.php:91
/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Stat                                                                                                                                                ement.php:165
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Persis                                                                                                                                                ters/BasicEntityPersister.php:279
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOf                                                                                                                                                Work.php:952
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOf                                                                                                                                                Work.php:335
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Entity                                                                                                                                                Manager.php:389
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/DAO/DAO.php:171
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobContr                                                                                                                                                ollerTest.php:137
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/ControllerTes                                                                                                                                                t.php:78
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobContr                                                                                                                                                ollerTest.php:29

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mime                                                                                                                                                Type' cannot be null

/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Stat                                                                                                                                                ement.php:165
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Persis                                                                                                                                                ters/BasicEntityPersister.php:279
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOf                                                                                                                                                Work.php:952
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOf                                                                                                                                                Work.php:335
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Entity                                                                                                                                                Manager.php:389
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/DAO/DAO.php:171
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobContr                                                                                                                                                ollerTest.php:137
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/ControllerTes                                                                                                                                                t.php:78
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobContr                                                                                                                                                ollerTest.php:29

FAILURES!
Tests: 17, Assertions: 52, Errors: 1.



So, I changed 'mimetype' to be null in the database and tried unittest,it errors out

Configuration read from /home/quotequadsco/public_html/xmlps/phpunit.xml

................E

Time: 3.77 seconds, Memory: 40.75Mb

There was 1 error:

1) ApiTest\Controller\ApiControllerTest::testSubmitActionCannotBeAccessedLoggedOut
Doctrine\DBAL\DBALException: An exception occurred while executing 'DELETE FROM user WHERE id = ?' with params [2347]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`quotequa_mysql`.`job`, CONSTRAINT `FK_FBD8E0F864B64DCC` FOREIGN KEY (`userId`) REFERENCES `user` (`id`))

/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91
/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:467
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php:591
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1029
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:362
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:389
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/DAO/DAO.php:184
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/TestHelper.php:68
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobControllerTest.php:149
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/ControllerTest.php:53

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`quotequa_mysql`.`job`, CONSTRAINT `FK_FBD8E0F864B64DCC` FOREIGN KEY (`userId`) REFERENCES `user` (`id`))

/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
/home/quotequadsco/public_html/xmlps/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:467
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php:591
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1029
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:362
/home/quotequadsco/public_html/xmlps/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:389
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/DAO/DAO.php:184
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/TestHelper.php:68
/home/quotequadsco/public_html/xmlps/module/Api/test/ApiTest/Controller/JobControllerTest.php:149
/home/quotequadsco/public_html/xmlps/vendor/xmlps/library/UnitTest/ControllerTest.php:53

FAILURES!
Tests: 17, Assertions: 53, Errors: 1.

**Comment by axfelix** [comment] 2015-01-06 16:08
Hi Vidhya,

You might want to try replacing the old DB, as I can't duplicate that.

**Comment by VidhyaApple** [comment] 2015-01-07 06:19
I deteted old DB and tried again but same error am getting, What would be the reason for this?

**Comment by VidhyaApple** [comment] 2015-01-07 14:40
Thank you so much ! I fixed that DB issue,now unit test is run successfully. I will try web service and let you know soon

**Comment by VidhyaApple** [comment] 2015-01-08 10:41
Hi axfelix,

I tried web service using below mentioned url,I think am not parsing correct url path, If so,pls guide me

    http://quotequads.co.in/pkp/public/api/job/submit?'email' => 'vidhu.chel@gmail.com' 'password' =>       'Vidhya@123' 'fileName' => 'document.docx' 'citationStyleHash' => 'c6de5efe3294b26391ea343053c19a84', 'fileContent' => '...'

Error:
    {"error":"File name (fileName) parameter is missing.","status":"error","flashMessages":[]}


In which location, should the file be stored?

**Comment by axfelix** [comment] 2015-01-08 17:44
Hey Vidhya,

Can I ask how you're making that POST request (eg with CLI curl or with PHP curl)? As I mentioned, it can be difficult to combine string and data parameters when using CLI curl.

**Comment by axfelix** [comment] 2015-01-08 18:03
There's example code for using the XMLPS API in lines 189 - 265 of this file, by the way: https://github.com/pkp/ojs-markup/blob/master/MarkupPluginUtilities.inc.php

**Comment by VidhyaApple** [comment] 2015-01-09 06:14
Hi axfelix,
   I feel sorry as I don't know how to use cURL. Some API usage guide is there in the API section of the xmlps home page.

API

There is a simple REST API available to submit, view and retrieve jobs from/to the server.

Submit

Submit a job to the server. The citationStyleHash is an internal identifier for the requested citaton style. A list of hashes can be retrieved through the citationStyleList API. The API will return the job id which can be used to retrieve the completed job later or to query the server for the job status.
*****************************************************************************************
URL: api/job/submit Request type: POST Parameters:

email
password
fileName
fileContent
citationStyleHash
I.e.

http://example.com/api/job/submit
POST parameters:
    'email' => 'user@example.com'
    'password' => 'passowrd'
    'fileName' => 'document.docx'
    'citationStyleHash' => 'c6de5efe3294b26391ea343053c19a84',
    'fileContent' => '...'
Example response:

{"status":"success","id":123}

*****************************************************************************************

So, I parse this 

    http://quotequads.co.in/pkp/public/api/job/submit?'email' => 'vidhu.chel@gmail.com' 'password' =>       'Vidhya@123' 'fileName' => 'document.docx' 'citationStyleHash' => 'c6de5efe3294b26391ea343053c19a84', 'fileContent' => '...'

in the address bar itslf. I din't use any php program.

**Comment by VidhyaApple** [comment] 2015-01-09 06:18
function apiRequest($plugin, $action, $params = array(), $isPost = false, $execute = true) {
		$journal = Request::getJournal();
		$journalId = $journal->getId();
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$params['email'] = $plugin->getSetting($journalId, 'markupHostUser');
		$params['password'] = $plugin->getSetting($journalId, 'markupHostPass');
		if ($isPost) {
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
			$params = array();
		}
		$apiUrl = self::apiUrl($plugin, $action, $params);
		if (!$execute) {
			return array('channel' => $ch, 'apiUrl' => $apiUrl);
		}
		curl_setopt($ch, CURLOPT_URL, $apiUrl);
		$response = curl_exec($ch);
		$response = json_decode($response, true);
		if (!$response) {
			$error = curl_error($ch);
			if (empty($error)) {
				$error = 'HTTP status: ' . curl_getinfo($ch, CURLINFO_HTTP_CODE);
			}
			$response = array(
				'status' => 'error',
				'error' => $error,
			);
		}
		curl_close($ch);
		return $response;
	}

function submitFile($plugin, $fileName, $filePath) {
		$journal = Request::getJournal();
		$journalId = $journal->getId();
		$params = array(
			'fileName' => $fileName,
			'fileContent' => file_get_contents($filePath),
			'citationStyleHash' => $plugin->getSetting($journalId, 'cslStyle'),
		);
		return self::apiRequest($plugin, 'submit', $params, true);
	}
The above mentioned program is from the https://github.com/pkp/ojs-markup/blob/master/MarkupPluginUtilities.inc.php which you suggested. 

I don't have any clue,what's the $plugin parameter in the code.So,
Can you pls tel me how to customize this code to use web service?

**Comment by axfelix** [comment] 2015-01-09 06:58
Hi Vidhya,

I'm afraid you can't just do an HTTP POST by pasting parameters into the URL bar like that -- GET will work like that for some APIs, including ours, but not POST. The code I linked you to is part of an Open Journal Systems plugin that's designed to utilize our API by sending Word files to our webservice for conversion to JATS; it makes use of php cURL.

**Comment by VidhyaApple** [comment] 2015-01-09 08:08
Ya I understand that. In place of $plugin parameter,what should I parse?

**Comment by axfelix** [comment] 2015-01-09 18:53
You shouldn't need that $plugin parameter at all if you're making a standalone call; I linked the plugin code to provide an example using php cURL, but the documentation on the main page of the repo should still be accurate: you need to provide credentials, a citation style, a filename, and file content. If you're not familiar with cURL, you might want to stick to the web frontend.

**Comment by VidhyaApple** [comment] 2015-01-10 05:51
I submitted the post using cURL. In both wen front end and also using cURL am getting the error page

![image](https://cloud.githubusercontent.com/assets/7392482/5690606/d554af88-98ba-11e4-9e22-50b460da7758.png)

**Comment by axfelix** [comment] 2015-01-12 18:27
Hi Vidhya,

I see several successfully completed jobs on our pkp-udev instance from you over the past several days, which is good! I assume you've been able to submit to our hosted instance no problem, and these errors are with your own instance? In this case, sharing some log files may be helpful so I can get a better idea of what's going wrong; you may not have installed it correctly, but I'll need more info to help.

**Comment by VidhyaApple** [comment] 2015-01-13 12:25
Actually the thing is, I don't get any error_log files when I run this instance. Just am getting the page which says error occurred during execution. How to track it then?. Its a run time error it seems.

And I want to say you, In pkp-udev, If I type the citation style in the text box it will display the option from which I could select the citation style. But in my instance,it doesn't display the option of citation styles. Is that the cause of an error?

**Comment by axfelix** [comment] 2015-01-13 15:51
Hm -- what does your /vendor install directory look like? I wonder if the
third party modules aren't being initialized properly using our install
script...


-alex

**Comment by VidhyaApple** [comment] 2015-01-16 04:55
Hi axfelix,
    Sorry for the delay.  

/vendor directory

![image](https://cloud.githubusercontent.com/assets/7392482/5771738/06508cac-9d6a-11e4-9fd5-573796ffb355.png)

**Comment by axfelix** [comment] 2015-01-16 17:17
Everything looks fine there too. I'm afraid I'm not sure what your issue is at this point ...

**Comment by axfelix** [comment] 2015-01-16 17:17
Everything looks fine there too. I'm afraid I'm not sure what your issue is
at this point ...


-alex

**Comment by VidhyaApple** [comment] 2015-01-17 05:01
Unit test also successfully executed. But I need to say, when running unittest I got an error
***********************************************************************************************************************
ApiTest\Controller\ApiControllerTest::testSubmitActionCannotBeAccessedLoggedO ut
Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO document (path, conversionStage, mimeType, size, jobId) VALUES (?, ?, ?, ?, ?)' with params ["\/tmp\/UNITTEST_document.txt", 10, null, 9, 130]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mimeType' cannot b e null
***********************************************************************************************************************

So, I changed 'mimetype' to be null in the database.Would it be the cause of an error?

**Comment by axfelix** [comment] 2015-01-19 18:01
Hi Vidhya,

Is it possible that there's some kind of permissions issue on your server so that the install isn't able to complete properly? That could be the cause of the DB issues you're experiencing -- I'm afraid I'm unable to duplicate them on my end.

**Comment by VidhyaApple** [comment] 2015-01-20 05:21
It doesn't seem like permission issue. 

INSERT INTO document (path, conversionStage, mimeType, size, jobId) VALUES (?, ?, ?, ?, ?)' with params ["\/tmp\/UNITTEST_document.txt", 10, null, 9, 130]:

This is sql statement. When creating database table mimeType was declared as NotNull. But in the above  mentioned sql,when trying to insert a null value to mimeType it gives an error.

**Comment by axfelix** [comment] 2015-01-20 05:36
What database are you running? Our reference server is on MySQL 5.5.40...

**Comment by VidhyaApple** [comment] 2015-01-20 13:16
MySQL Version	5.5.40-cll

**Comment by axfelix** [comment] 2015-10-02 16:48
Hi Vidhya,

Is this still an issue? We've changed the unit tests a bit so you might not be having this problem anymore -- would be happy if I could close this.

**Closed** 2015-10-14 18:22 UTC
