### ISSUE TITLE
Add epub conversion to stack

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#11] opened 2015-07-24 05:52 UTC
1. Clone `HtmlConversion` and associated tests.
1. Modify conversion to produce epub instead.
1. Edit `README.md` to include new module.

**Comment by crism** [comment] 2015-07-28 19:39
I’m planning a new module, `EpubConversion`, modeled on `HtmlConversion`, with the same interface. Does that sound right?

**Comment by axfelix** [comment] 2015-07-28 19:41
Yep!

**Comment by crism** [comment] 2015-07-30 02:17
Hm. I note that `HtmlConversionTest\Model\Converter\HtmlTest::testConversion()` only tests that the input and output files differ, and that the output is a zip file. Was testing the actual contents of the output found too difficult, before I start down that road?

**Comment by axfelix** [comment] 2015-07-30 02:18
it definitely wouldn't be too difficult to, say, also verify that the results are valid XML, but I don't think we need to go farther than that in the tests.

**Comment by crism** [comment] 2015-07-30 02:20
What’s our target Epub format? 3.0.1 is the latest, which is supposed to be backward-compatible with 3.0 (which is 4 years old). And is the HTML payload from the HTML conversion adequate for now, or do we need more or different features?

**Comment by axfelix** [comment] 2015-07-30 02:24
This guy right here seems pretty well maintained, and I'm all in favour of not having to modify it much: https://github.com/eirikhanssen/jats2epub

**Comment by axfelix** [comment] 2015-07-30 02:25
generally speaking I'd much rather spend time polishing meTypeset's JATS output so that it can be used as input for off-the-shelf transformations than I would modifying that jats2epub module, unless there are special circumstances.

**Comment by crism** [comment] 2015-07-30 02:34
jats2epub looks good. It’s GPL—what’s our license? (We should add a top-level `LICENSE` file…)

**Comment by axfelix** [comment] 2015-07-30 02:52
We probably need to go Apache/MIT/BSD; the modular structure should get around us being hamstrung by any of the GPL dependencies, but I don't think this stack is functionally "clean" enough to be GPLed itself

**Comment by crism** [comment] 2015-07-30 05:52
License question should probably be a separate issue.

Anyway: https://github.com/eirikhanssen/jats2epub looks good, as I said. The question then is how best to integrate it. It includes XSLT, plus a Calabash pipeline and a further shell script wrapper around that. We could take the XSLT and reimplement the pipeline in PHP, or just shell out to the entire `jats2epub` process.

In either case, there’s a political or style question—do we treat `jats2epub` as a package in Composer, or assets within the `EpubConversion` module? Do we fork the project?

**Comment by axfelix** [comment] 2015-07-30 05:54
@jalperin Thoughts welcome. I need a good reason not to shell out.

**Comment by crism** [comment] 2015-07-30 05:57
Hrm. Some of the `jats2epub` XSLT files are XSLT 2.0, which means `libxslt` won’t work with them. We would need Saxon to handle those, which means we may as well shell out to Calabash.

**Comment by crism** [comment] 2015-07-30 06:02
Hrm²… but I think the few XSLT 2.0 features they’re using (element-only variables, node identity) can be retrograded to XSLT 1.0. That definitely means forking or modifying the system…

**Comment by axfelix** [comment] 2015-07-30 06:04
If you think you can do so with no loss of functionality, and it'll be edifying, and it means no Java, then it's probably worth forking to use 1.x...

**Comment by crism** [comment] 2015-07-30 06:21
Forking `jats2epub` seems like a good idea. I don’t have permission to fork it into the PKP project, though.

**Comment by jalperin** [comment] 2015-07-30 06:22
What is the repo we need to fork? I can make the fork on the pkp account

**Comment by crism** [comment] 2015-07-30 06:24
@jalperin: https://github.com/eirikhanssen/jats2epub

**Comment by jalperin** [comment] 2015-07-30 06:24
done: https://github.com/pkp/jats2epub

**Comment by crism** [comment] 2015-07-30 06:26
Awesome, thanks.

**Comment by crism** [comment] 2015-07-30 10:06
Had to do a little work to get `jats2epub` to work right, but the results seem acceptable, or at least a good starting point. Will look at downgrading it to XSLT 1.0… I think it will work pretty straightforwardly.

**Comment by axfelix** [comment] 2015-07-30 14:39
Excellent.

**Comment by crism** [comment] 2015-08-05 22:59
Hrm… there are (of course) a couple of really tricky bits hiding in here. As XSLT 1.0 is Turing-complete, it’s *possible*, of course, but may involve more wholesale rewriting than just a few tweaks.

How horribly disruptive would requiring Saxon be?

**Comment by axfelix** [comment] 2015-08-06 00:35
Not terribly, as long as it's a simple CLI call. If it'd be more than a day of work to port it to 1.0 then I'm perfectly happy to let it be.

**Comment by crism** [comment] 2015-08-08 06:02
So, `jats2epub` always makes working files, and leaves them behind. We can clean up that mess, of course. Would it be cricket to always do the work in `/tmp` and move the interesting results back to the target?

**Comment by crism** [comment] 2015-08-08 07:05
Actually, since `jats2epub` hard-codes its output directory names, we really need our own temporary directories, else we run a risk of multiple conversions treading on each others’ toes. We also need to clean up after ourselves… Where’s the best place for utility functions like a wrapper for UNIX `mktemp` and a PHP version of `rm -rf`? I’m currently tempted to put it in `Xmlps\Command\Command`, but I’m not sure that’s appropriate.

**Comment by crism** [comment] 2015-08-08 07:18
Well, it makes an epub. Is it a good one? That’s another question. While I’m working on integrating this into the queue, I welcome suggestions for tests to add to assess the output beyond its simple existence.

**Comment by crism** [comment] 2015-08-08 07:43
What should the output file be called? The HTML queue names its output `html.zip`; it seems like `epub.epub` is a bit trivial, but we don’t seem to have much more information to give it a better name.

**Comment by crism** [comment] 2015-08-08 07:49
The basic functionality is now there. I don’t yet have a working Web service, so it would be nice if someone else could verify that the queue functionality actually works *in situ*.

**Comment by axfelix** [comment] 2015-08-09 21:04
I definitely agree with putting utility functions somewhere in https://github.com/pkp/xmlps/tree/master/vendor/xmlps/library but I'm also not sure if command/command is appropriate; up to you. `epub.epub` is silly but I agree that it's probably the best way to follow our existing convention for now (until we incorporate some sort of automatic naming of output files based on the input filename, which may as well be an open issue now that you've got the hang of this project). Will verify on the server shortly. Thanks!

**Comment by axfelix** [comment] 2015-08-09 21:59
issue/11 branch is checked out on the server now and the good news is that it's not causing any issues with the existing functionality but epub doesn't seem to be in the list of files being returned: http://pkp-udev.lib.sfu.ca/manager/details/id/1541

**Comment by axfelix** [comment] 2015-08-09 22:00
hopefully I get a chance to look into this myself before the conference.

**Comment by axfelix** [comment] 2015-08-09 22:01
Judging from http://pkp-udev.lib.sfu.ca/admin/system-log/list it seems like the new module isn't firing at all

**Comment by axfelix** [comment] 2015-08-09 22:05
Oh wait, I forgot to do a composer update :) -- hold please.

**Comment by axfelix** [comment] 2015-08-09 22:10
Hmmmm. Composer update has not fixed epub module, but has broken parscit (albeit gracefully, in that bibtex no longer being returned): http://pkp-udev.lib.sfu.ca/manager/details/id/1542

**Comment by axfelix** [comment] 2015-08-09 22:12
I probably should've diffed Michael's old fork of Parscit on the server against upstream to see if we /had/ made any modifications I'd forgotten about to assist with calling it ...

**Comment by crism** [comment] 2015-08-10 05:10
Unfortunately, I think that ParsCit fork isn’t available anywhere publicly… I hope someone else has it checked out! Really should be a new issue…

**Comment by crism** [comment] 2015-08-10 05:15
But back to this issue… I assume there’s some kind of command-and-control thing that I need to register the epub path with. Trying to figure that out now.

**Comment by crism** [comment] 2015-08-10 05:16
BTW, the transparent failure of ParsCit suggests that more thorough tests are needed. Not ready to file a separate issue on that, but something to think about.

**Comment by crism** [comment] 2015-08-14 20:52
I think this is done, and will close after merging. There are numerous tweaks that could be done to streamline the workflow and improve the output, but the basic functionality is there.

**Comment by axfelix** [comment] 2015-08-14 20:54
Excellent. Should test on the server again before we close this.

**Comment by axfelix** [comment] 2015-08-17 17:15
This seems to still be silently not firing, unfortunately:

garnett@pkp-udev:/var/www$ git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/pkp/xmlps
   97b77a2..73b03e9  master     -> origin/master
Already up-to-date.
garnett@pkp-udev:/var/www$ git status
# On branch issue/11
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	.bash_history
#	.composer/
#	.fontconfig/
#	public/parsingdev/
#	vendor/eirikhanssen/
nothing added to commit but untracked files present (use "git add" to track)

http://pkp-udev.lib.sfu.ca/manager/details/id/1554

**Comment by crism** [comment] 2015-08-18 20:14
The merge seems to have worked; master is definitely ahead of the (now-deleted) branch. Closing this.

**Comment by axfelix** [comment] 2015-08-18 22:24
I'm happy to see it merged in, but it still didn't actually seem to be working on the newest issue 11 branch yesterday on the server ... was the merge supposed to have fixed that?

**Comment by crism** [comment] 2015-08-19 00:18
You did the merge, didn’t you? I can reopen the branch to fix additional issues. I thought the problems were related to the dependencies, triggered when you re-ran Composer, and that those were addressed. Sorry if I got that wrong…

**Comment by axfelix** [comment] 2015-08-20 19:47
I did do the merge, but as far as I can tell it's still not firing after pulling in all the dependencies -- is it possible it's still not registered with some part of the stack?

**Comment by crism** [comment] 2015-08-20 20:20
I’m not sure. I still don’t understand what triggers the queue workers. The database being in a particular state, apparently, but I think that there are two competitors for the epub predecessor. Hrm, and there may be a bug in the worker:
```php
        if (!$document = $job->getStageDocument(JOB_CONVERSION_STAGE_BIBTEXREFERENCES)) {
            !$document = $job->getStageDocument(JOB_CONVERSION_STAGE_NLMXML);
        }
```
That `!$document` assignment don’t look right. It was copied from `HtmlJob.php`, though, so the bug may be pervasive, and never tested.

**Comment by axfelix** [comment] 2015-08-20 20:57
Yeah, this is actually the stuff that's confusing the hell out of me w/r/t trying to implement the merging of the CERMINE and meTypeset outputs in my module. I might see if I can pull someone else in from the team; a lot of these PHP-isms still aren't my forte.

**Comment by axfelix** [comment] 2015-08-24 16:17
Michael's advice for now is to look over the old commit messages and see if we can't find what we're missing that way -- which is sensible. Let's see where we get by midweek?

**Comment by axfelix** [comment] 2015-08-24 16:33
From looking at 

https://github.com/pkp/xmlps/blob/master/module/Manager/src/Manager/Model/Queue/Manager.php#L120

It seems we could be missing something for the ePub module along the lines of https://github.com/pkp/xmlps/blob/7260971eec388544ae3d3da1ba91c7d71fc06c91/module/Manager/src/Manager/Model/Queue/Manager.php#L141

**Comment by crism** [comment] 2015-08-25 07:57
Yes, I think you’ve nailed it, @axfelix. I had grep’d for references to the modules, but had missed that instance of the litany of magic numbers. It’s probably worth grep’ing for those, too.

**Comment by crism** [comment] 2015-08-25 20:43
Indeed, this is exactly the logic I was wondering about. I still can’t successfully test the full stack locally—can you see if this latest does the trick, @axfelix? This will be integrated into #19, as well.

**Comment by axfelix** [comment] 2015-08-25 20:43
Yup, on it by EOD today. I swear I'm getting close to finishing my conference backlog :)

**Comment by axfelix** [comment] 2015-08-25 23:13
Well, it's firing now, but it seems to be dying :)

2015/08/25 16:10:30
INFO	epubconversion.converter.errorGlob
2015/08/25 16:10:30
DEBUG	epubconversion.converter.executeCommandOutputLog
2015/08/25 16:10:30
DEBUG	epubconversion.converter.startJats2epub

If you run your current local version of jats2epub against http://pkp-udev.lib.sfu.ca/manager/download/id/3653, what's the output? (That link will require admin credentials for our live instance to follow, btw -- ping me in IRC if you don't have them handy).

**Comment by crism** [comment] 2015-08-26 08:01
The `epubconversion.converter.errorGlob` means it couldn’t find the output file. (And hm, I thought I’d translated all those tokens!) Is it possible the Web server doesn’t have write permissions to `/tmp` or something? It would help if `epubconversion.converter.executeCommandOutputLog` actually gave the output like it’s supposed to…

**Comment by crism** [comment] 2015-08-26 08:10
Sorry, I had only worked on the translations for #19. This should help.

**Comment by axfelix** [comment] 2015-08-26 17:59
Looks like jats2epub.Xuwlw is being created in /tmp owned by root with 700 permissions... I think our documentation currently suggests to run start_queues as root, so this might be a result of that?

**Comment by crism** [comment] 2015-08-26 18:37
It’s possible. I had similar problems with #19—I created a test page to launch the queues from within the server context, and that worked; now I’m trying to make it part of the app.

**Comment by axfelix** [comment] 2015-08-26 18:39
Would it be much a problem in the meantime for the process to create the tmp directory with 777? It shouldn't be web accessible under any circumstances, and the server has no shell users...

**Comment by crism** [comment] 2015-08-26 18:47
I have another meeting in a couple of minutes, but it should be possible to `chmod` the result of `mktemp`, after line 106 of `Epub.php`. Starting the queues as the Web server user is definitely the superior long-term option, though.

**Comment by axfelix** [comment] 2015-08-26 18:48
Yep, agreed. Well, let me 777 that tmp directory for now and see if that works ...

**Comment by axfelix** [comment] 2015-08-26 18:52
Oh, I see, the issue is that it creates a new /tmp directory each time :)

**Comment by axfelix** [comment] 2015-08-26 19:15
Or -- actually, is there a reason we aren't following whatever the output file structure of the other modules is?

**Comment by axfelix** [comment] 2015-08-26 19:43
Oh, right, hardcoded output directories in jats2epub. Except can't we get around that? https://github.com/eirikhanssen/jats2epub/blob/bb49581ad74f22917373ae7e5c398ccc6aeae7d2/programs/xmlcalabash/docs/reference/javasetup.html#L159

**Comment by crism** [comment] 2015-08-26 21:16
Right, `jats2epub` has all kinds of hard-coded output cruft. I did make that all relative, so we can be sure that we’re only writing in our own temp directory, but I wanted to use a temp directory because of all the excess it leaves behind. My thought was that we could clean that up, but I thought we’d get it up and running as-is first. Maybe that wasn’t the best plan.

**Comment by axfelix** [comment] 2015-08-26 21:18
I don't think it's a particularly bad plan, honestly... it's just that when 777ing a directory comes to seem like the least invasive change you can make in order to make something work, you have to wonder aloud whether it's a good call. But honestly I think it's probably fine; I'm not as aware of our other modules needing to clean up after themselves to the same extent because most of them only actually output files that we want.

**Comment by axfelix** [comment] 2015-08-26 21:28
...and, of course, we can't 777 it from the php without root permissions because it's getting created with 700 for some reason, even though it shouldn't be inheriting that from /tmp.

I vote to veto mktemp (or alternately switch it to make a tmp directory within /var/www). Causing too many headaches.

**Comment by crism** [comment] 2015-08-26 21:34
OK… the problem is that `jats2epub` has fixed *relative* directories (`output_working` and `output_final`) that will step on each other if two jobs run at once.

It seemed like `mktemp` was the easiest way to get a private working space… I welcome other suggestions.

**Comment by crism** [comment] 2015-08-26 21:40
I added an explicit `chmod` and a status check on `jats2epub`. I suspect that `jats2epub` was failing (just based on the time stamps—it’s not that fast!) due to the permission problems, and the `glob` problem was just a symptom of that.

**Comment by crism** [comment] 2015-08-26 21:40
If that works, I can go back to working on #19, which should mitigate this problem.

**Comment by axfelix** [comment] 2015-08-26 21:41
Will the chmod work if it's trying to chmod a directory that was created with 700 and root:root, though? Might want to try doing mktemp with --tmpdir=/var/www/someplace instead to see if that works any differently ... though I'm still not sure where mktemp's output in /tmp is inherting permissions from.

**Comment by crism** [comment] 2015-08-26 21:43
`mktemp` always creates a directory owned by its user. The job appears to be running as `root` for some reason, but the process owner always ought to be able to `chmod` its own directory.

**Comment by axfelix** [comment] 2015-08-26 21:44
Aha, yup, that explains it -- probably related to start_queues.sh running as root. Thanks for clarifying that for me.

**Comment by crism** [comment] 2015-08-26 21:47
So #19 would fix this, but the `chmod` ought to cover it for now.

**Comment by axfelix** [comment] 2015-08-26 21:47
just pulled newest issue/11, ran on server, and ... directory still being created with 700 permissions, job failing, and chmod not firing as far as I can tell :(

**Comment by crism** [comment] 2015-08-26 21:52
What does the log say? There should be more finely-grained information in there now.

**Comment by axfelix** [comment] 2015-08-26 21:53
Unfortunately seems not:

2015/08/26 14:45:41
INFO	epubconversion.converter.errorGlob
2015/08/26 14:45:41
DEBUG	epubconversion.converter.executeCommandOutputLog

**Comment by crism** [comment] 2015-08-26 21:59
Hm, `executeCommandOutputLog` ought to have more (helpful) information with it. Try the latest.

**Comment by axfelix** [comment] 2015-08-26 22:41
Different, but still nothing of much use:

2015/08/26 15:38:59
INFO	epubconversion.converter.errorGlob
2015/08/26 15:38:59
DEBUG	epubconversion.converter.executeCommandOutputLog
2015/08/26 15:38:59
DEBUG	epubconversion.converter.startJats2epub
2015/08/26 15:38:59
DEBUG	epubconversion.converter.startMktemp
2015/08/26 15:38:59
DEBUG	epubconversion.converter.startLog

**Comment by crism** [comment] 2015-08-26 22:45
You really shouldn’t be getting untranslated tokens in the log… are `module/Application/language/en_US.[pm]o` up to ee9dd6e44ca64f5cd253e9b547ea49386444f383?

**Comment by axfelix** [comment] 2015-08-26 22:46
Everything's up to date with newest issue/11 unless Git is playing some kind of exciting trick on me ... and I'm still fairly sure it's the chmod that's not firing.

**Comment by crism** [comment] 2015-08-26 22:48
Without seeing the output from `jats2epub`, I can’t be sure. There *really* shouldn’t be untranslated tokens, if `en_US.mo` is up to date; that makes me nervous. You could throw a `die();` into `Epub.php`, right after the `chmod` call, to see what’s left in the temp directory.

**Comment by axfelix** [comment] 2015-08-26 23:10
Well, the temp directory isn't getting torn down or written to at the moment, so I have a pretty good idea of what's in there :)

No idea about the tokens, though ...

**Comment by crism** [comment] 2015-08-26 23:26
OK, so `jats2epub` is failing. Presumably for the same permissions reasons… If you’ve got a better idea of where to put the output and how to find it, go for it. Otherwise, I think #19 is our best bet to fix this.

**Comment by axfelix** [comment] 2015-08-27 20:39
Not to house of cards this whole series of issues, but if the outputTmpPath logic from the PdfConversion module that I attempted to borrow for the XML merge in https://github.com/pkp/xmlps/issues/15 makes any sense to you (I was struggling with it), that might not be the worst course of actoin.

**Comment by crism** [comment] 2015-08-27 21:56
We forgot to restart the queues, which is why the log tokens weren’t being translated, too. Starting queues à la #19 worked; now I wonder if we can back out the `chmod` change.

**Closed** 2015-08-27 22:12 UTC
Labels: enhancement
